SYNONYM_MAP = {
    "acct": "accounting",
    "aero": "aerospace engineering",
    "ai": "artificial intelligence",
    "assoc": "association",
    "athletic": "athletics",
    "bio": "biology",
    "bioeng": "biomedical engineering",
    "biz": "business",
    "campus": "campus ministry",
    "chem": "chemistry",
    "civil": "engineering",
    "cs": "computer science",
    "db": "database",
    "econ": "economics",
    "elec": "electrical engineering",
    "eng": "english",
    "fin": "finance",
    "frat": "fraternity",
    "gov": "government",
    "greek": "greek life",
    "hist": "history",
    "hr": "human resources",
    "intl": "international",
    "it": "information technology",
    "lgbtq": "lesbian gay queer trans",
    "gay": "lgbtq",
    "lesbian": "lgbtq",
    "queer": "lgbtq",
    "trans": "lgbtq",
    "bisexual": "lgbtq",
    "lgbtqia": "lgbtq lesbian gay queer trans bisexual",
    "lit": "literature",
    "mech": "mechanical engineering",
    "med": "medicine",
    "mgmt": "management",
    "ministry": "ministry",
    "mkt": "marketing",
    "ml": "machine learning",
    "neuro": "neuroscience",
    "nsls": "national society of leadership and success",
    "org": "organization",
    "outreach": "community outreach",
    "pharm": "pharmacy",
    "pol": "political science",
    "pre-med": "pre-medicine",
    "pre-vet": "pre-veterinary medicine",
    "professional": "professional",
    "psych": "psychology",
    "pt": "physical therapy",
    "pta": "physical therapy assistant",
    "rotc": "reserve officers training corps",
    "sci": "science",
    "service": "community service",
    "soc": "society",
    "swe": "software engineering",
    "ttu": "texas tech university",
    "unt": "university of north texas",
    "ut": "university of texas",
    "vet": "veterinary",
    "web": "development",
}