SYNONYM_MAP = {
    "acct": "acct accounting",
    "aero": "aero aerospace engineering",
    "ai": "ai artificial intelligence",
    "assoc": "assoc association",
    "athletic": "athletic athletics",
    "bio": "bio biology",
    "bioeng": "bioeng biomedical engineering",
    "biz": "biz business",
    "campus": "campus ministry",
    "chem": "chem chemistry",
    "civil": "civil civil engineering",
    "cs": "cs computer science",
    "db": "db database",
    "econ": "econ economics",
    "elec": "elec electrical engineering",
    "eng": "eng english",
    "fin": "fin finance",
    "frat": "frat fraternity",
    "gov": "gov government",
    "greek": "greek life",
    "hist": "hist history",
    "hr": "hr human resources",
    "intl": "intl international",
    "it": "it information technology",
    "lgbtq": "lgbtq lesbian gay queer trans",
    "gay": "gay lgbtq",
    "lesbian": "lesbian lgbtq",
    "queer": "queer lgbtq",
    "trans": "trans lgbtq",
    "lgbtqia": "lgbtqia lgbtq lesbian gay queer trans",
    "lit": "lit literature",
    "mech": "mech mechanical engineering",
    "med": "med medicine",
    "mgmt": "mgmt management",
    "ministry": "ministry",
    "mkt": "mkt marketing",
    "ml": "ml machine learning",
    "neuro": "neuro neuroscience",
    "nsls": "nsls national society of leadership and success",
    "org": "org organization",
    "outreach": "outreach community outreach",
    "pharm": "pharm pharmacy",
    "pol": "pol political science",
    "pre-med": "pre-med pre-medicine",
    "pre-vet": "pre-vet pre-veterinary medicine",
    "professional": "professional",
    "psych": "psych psychology",
    "pt": "pt physical therapy",
    "pta": "pta physical therapy assistant",
    "rotc": "rotc reserve officers training corps",
    "sci": "sci science",
    "service": "service community service",
    "soc": "soc society",
    "swe": "swe software engineering",
    "ttu": "ttu texas tech university",
    "unt": "unt university of north texas",
    "ut": "ut university of texas",
    "vet": "vet veterinary",
    "web": "web web development",
}